name 'puppet-pick'
version '0.0.1'
source 'git://github.com/glarizza/puppet-pick.git'
author 'Gary Larizza'
license 'Apache 2.0'
summary 'Puppet function for data-lookups based on a provided lookup-order'
description 'Puppet function for data-lookups based on a provided lookup-order'
project_page 'https://github.com/glarizza/puppet-pick'
